### ISSUE TITLE
Cargo install fails

### ISSUE THREAD

**Issue by evavh** [dvdsk/rbtw#3]
When I run `cargo install rbtw`, it fails with the following error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/focus/.cargo/registry/src/github.com-1ecc6299db9ec823/rbtw-1.0.0/src/main.rs:1:12
  |
1 | #![feature(unix_chown)]
  |            ^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `rbtw` due to previous error
error: failed to compile `rbtw v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-install588iqB`
```

**Comment by dvdsk** [comment]
there should now be a warning and hint on how to install using nightly, can you try again?

**Comment by evavh** [comment]
Now I get the following error: `error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed`.

**Comment by dvdsk** [comment]
Sorry this took so long, I kinda forgot about this :(

You can fix the error with `rustup install nightly`. I have added instruction to the Readme and a clearer error will now appear mentioning that fix.

Please reopen the issue if you have any more trouble!
